quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/nursery_db
quarkus.datasource.username=postgres
quarkus.datasource.password=maria17
quarkus.hibernate-orm.log.sql=true

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.redis.hosts=redis://localhost:6379

quarkus.cache.caffeine."plant-cards-cache".expire-after-access=PT15M
quarkus.log.category."io.quarkus.cache".level=DEBUG
